project:
  type: website
  output-dir: .

website:
  title: ""
  
  navbar:
    left:
      - href: index.qmd
        text: Finc About Us
      - href: r_adopt.qmd
        text: Adopting R & Research Software
      - href: dscience.qmd
        text: Statistics - Data Science
      - href: About.qmd
        text: About Audrey
      - href: Talks.qmd
        text: Talks
    
    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

