project:
  type: website

website:
  title: "finc"
  navbar:
    left:
      - href: index.qmd
        text: Finc About Us
      - href: about.qmd
      - href: dscience.qmd
        text: Data Science
      - href: Software.qmd
        text: Research Software
      - href: blog.qmd
        text: Blog
    
    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

