project:
  type: website
  output-dir: docs

website:
  title: ""
  
  navbar:
    left:
      - href: index.qmd
        text: Finc About Us
      - href: r_adopt.qmd
        text: Adopting R & Research Software
      - href: ghostwriting.qmd
        text: Ghostwriting
      - href: dscience.qmd
        text: Data Science
      - href: blog.qmd
        text: Blog
      - href: about.qmd
        text: About Audrey
    
    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

