project:
  type: website

website:
  title: "finc"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: blog.qmd
        text: Blog
      - Blog.qmd
      - href: software.qmd
      #   text: Software
      # - software.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

