---
title: "About Audrey"
---

I am the owner of Finc Research. While it is a remote company, I am based in Basel, Switzerland.

I've lived in Australiasia, Asia and Europe. I speak eight languages across these continents and am a seasoned Data Scientist, trained in Statistics at the University of Zürich, also in Switzerland.

I am also a season Registered Nurse licensed in Australia. I earned my Master of Nursing from the University of Sydney. I recently worked at a major paediatric hospital in my origin of city of Melbourne, otherwise known as Naarm, Australia. My work in ICU included being part of the COVID workforce in 2021. No, I am not providing ANY services pertaining to this.

My philosophy in ghostwriting is to learn about the client, their audience and take great care in honing their voice and means to its end.


In my spare time, I write open source software and am an active member of research software and programming language groups in pursuit of bettering the quality of research tools for Science.

Below are my current industry memberships

- OpenStatsWare 
- R consortium Health Technology Assessment working group
- R/Pharma organising committee







